### ISSUE TITLE
OUTPUT DELAY SLOWER THAN INPUT

### ISSUE THREAD

**Issue by Classsic** [rom1v/delay#1]
Hi, great tool, thanks for create it.
I try to delay ffmpeg output, something like this "ffmpeg -i rtsp://localhost/1.sdp -vcodec copy -f flv -|delay 15s |ffmpeg  -i - -an -f flv -acodec copy -vcodec copy  rtmp://localhost:1936/delay/$1 2>/var/log/$1.log&.
When the input have lower bitrate (200 kb) ffmpeg keep the fps, but if the bitrate is higher than 1500 kb, ffmpeg only can process the half fps and the stream is corrupt.
If I delete the delay 15s, ffmpeg have not problem with high bitrate.
This happen in small and old machine P4 with 1GB ram ddr1.
Thanks.

**Comment by rvimont** [comment]
By default, the buffer is 1M, so for 15s the maximum bitrate is 1M/15s=~70kbps. So even at 200kbps it will not work after some time.

For 1500kbps during 15s, you need a buffer of 22,5M (at least).

Try:

~~~
ffmpeg … | delay -b30m 15s | ffmpeg…
~~~

**Comment by rom1v** [comment]
By default, the buffer is 1MiB, so for 15s the maximum bitrate is 1MiB/15s=~68KiBps. So even at 200KBps it will not work after some time.

For 1500KBps during 15s, you need a buffer of 22,5Mb (at least, so use 30Mib).

Try:

```
ffmpeg … | delay -b30m 15s | ffmpeg …
```

**Comment by Classsic** [comment]
This work great! Thanks!
