### ISSUE TITLE
DELAY not respect time when buffer is greater than what we need.

### ISSUE THREAD

**Issue by Classsic** [rom1v/delay#2]
Hi, I found, a little incosistence when use delay with ffmpeg. If the input have variable bitrate (200k up to 2000k) and I need 10s of delay, I use this "delay -b20000k 10s" but, if input stablish in 200k the delay is increased up to 15s. How I can get more accuracy with variable bitrate input.

**Comment by rom1v** [comment]
Probably that `ffmpeg` actually outputs sometimes faster than 2000kbps.

Just use a bigger buffer:

```
delay -b100m 10s
```

**EDIT:** Sorry, I misread. You mean that the input is 200kbps, you use `delay -b20000k 10s`, and you observe a delay of 15s? That's weird.

**Comment by Classsic** [comment]
Yes,that's happens....

**Comment by rvimont** [comment]
What's bitrate is measured by `pv`?

~~~
ffmpeg … | pv > /dev/null
~~~

**Comment by rom1v** [comment]
What bitrate is measured by `pv`?

```
ffmpeg … | pv > /dev/null
```

**Comment by Classsic** [comment]
ffmpeg has as input variable bitrate camera, so bitrate change over the time..from 200 to 2000 kbps

**Comment by rom1v** [comment]
Then what is the delay output bitrate?

```
ffmpeg … | delay -b 20m 10s | pv > /dev/null
```

(after 10s)

What is your real command after `delay`?

**Comment by rom1v** [comment]
up?
